// <auto-generated/>
using System.Reflection;
using System.Windows;

[assembly: AssemblyTitleAttribute("WPFTagControl")]
[assembly: AssemblyProductAttribute("WPFTagControl")]
[assembly: AssemblyDescriptionAttribute("WPF control for tags/tokens")]
[assembly: AssemblyVersionAttribute("0.4.0")]
[assembly: AssemblyFileVersionAttribute("0.4.0")]
[assembly: ThemeInfoAttribute(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.0";
        internal const string InformationalVersion = "0.4.0";
    }
}
