// <auto-generated/>
using System.Reflection;
using System.Windows;

[assembly: AssemblyTitleAttribute("WPFTagControl")]
[assembly: AssemblyProductAttribute("WPFTagControl")]
[assembly: AssemblyDescriptionAttribute("WPF control for tags/tokens")]
[assembly: AssemblyVersionAttribute("0.4.2")]
[assembly: AssemblyFileVersionAttribute("0.4.2")]
[assembly: ThemeInfoAttribute(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]