// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("WPFTagControl")]
[assembly: AssemblyProductAttribute("WPFTagControl")]
[assembly: AssemblyDescriptionAttribute("WPF control for tags/tokens")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
        internal const string InformationalVersion = "0.1.0";
    }
}
